create table if not exists public.schools (
  id integer generated by default as identity primary key,
  name varchar(120) not null unique,
  description text not null default '',
  fit_text text not null default '',
  results_text text not null default '',
  official_url varchar(500) not null default '',
  subjects varchar(500) not null default '',
  monthly_price_from integer not null default 0 check (monthly_price_from >= 0),
  price_text text not null default '',
  price_comment text not null default '',
  scale_reputation text not null default '',
  format_text text not null default '',
  support_text text not null default '',
  homework_text text not null default '',
  strengths text not null default '',
  weaknesses text not null default '',
  review_summary text not null default '',
  evidence_types varchar(200) not null default '',
  teachers_text text not null default '',
  teachers_score double precision not null default 7 check (teachers_score between 0 and 10),
  practice_score double precision not null default 7 check (practice_score between 0 and 10),
  feedback_score double precision not null default 7 check (feedback_score between 0 and 10),
  curator_score double precision not null default 7 check (curator_score between 0 and 10),
  platform_score double precision not null default 7 check (platform_score between 0 and 10),
  workload_score double precision not null default 7 check (workload_score between 0 and 10),
  price_quality_score double precision not null default 7 check (price_quality_score between 0 and 10),
  review_count integer not null default 0 check (review_count >= 0),
  is_active boolean not null default true,
  verified_at timestamp with time zone
);

create table if not exists public.teachers (
  id integer generated by default as identity primary key,
  school_id integer not null references public.schools(id) on delete cascade,
  name varchar(160) not null,
  subject varchar(120) not null,
  description text not null default '',
  rating double precision not null default 7 check (rating between 0 and 10),
  review_summary text not null default '',
  social_url varchar(500) not null default '',
  source_url varchar(500) not null default '',
  evidence_type varchar(120) not null default '',
  is_active boolean not null default true,
  unique (school_id, name, subject)
);

create table if not exists public.courses (
  id integer generated by default as identity primary key,
  school_id integer not null references public.schools(id) on delete cascade,
  subject varchar(120) not null,
  name varchar(200) not null,
  price_from integer check (price_from is null or price_from >= 0),
  price_text text not null default '',
  format_text text not null default '',
  support_text text not null default '',
  practice_text text not null default '',
  tariffs_json text not null default '[]',
  source_url varchar(500) not null default '',
  verified_at timestamp with time zone,
  is_active boolean not null default true
);

create table if not exists public.users (
  id integer generated by default as identity primary key,
  telegram_id bigint not null unique,
  created_at timestamp with time zone not null default now()
);

create table if not exists public.reviews (
  id integer generated by default as identity primary key,
  user_id integer not null references public.users(id) on delete restrict,
  school_id integer not null references public.schools(id) on delete cascade,
  teacher_id integer references public.teachers(id) on delete cascade,
  criterion varchar(80),
  criteria_json text,
  score double precision not null check (score between 1 and 5 and score * 2 = trunc(score * 2)),
  text_positive text not null default '' check (char_length(text_positive) <= 4000),
  text_negative text not null default '' check (char_length(text_negative) <= 4000),
  moderation_status varchar(30) not null default 'pending'
    check (moderation_status in ('pending', 'approved', 'rejected')),
  verified boolean not null default false,
  proof_file_id varchar(500),
  proof_file_type varchar(30) check (proof_file_type is null or proof_file_type in ('photo', 'document')),
  proof_delete_after timestamp with time zone,
  proof_consent boolean not null default false,
  created_at timestamp with time zone not null default now(),
  check (teacher_id is null or criterion is null)
);

create table if not exists public.review_criterion_scores (
  review_id integer not null references public.reviews(id) on delete cascade,
  criterion varchar(80) not null check (criterion in (
    'teachers_score', 'practice_score', 'feedback_score', 'curator_score',
    'platform_score', 'workload_score', 'organization_score',
    'explanation', 'practice', 'feedback', 'tempo', 'communication'
  )),
  score double precision not null check (score between 1 and 5 and score * 2 = trunc(score * 2)),
  primary key (review_id, criterion)
);

create table if not exists public.events (
  id integer generated by default as identity primary key,
  telegram_id bigint not null,
  event_name varchar(80) not null,
  metadata_json text,
  created_at timestamp with time zone not null default now()
);

create table if not exists public.rating_snapshots (
  school_id integer primary key references public.schools(id) on delete cascade,
  editorial_score numeric(3,1) not null check (editorial_score between 0 and 10),
  verified_user_score numeric(2,1) check (verified_user_score between 1 and 5),
  verified_review_count integer not null default 0 check (verified_review_count >= 0),
  final_score numeric(3,1) not null check (final_score between 0 and 10),
  is_preliminary boolean not null default true,
  calculated_at timestamp with time zone not null default now()
);

create table if not exists public.rating_runs (
  id bigint generated always as identity primary key,
  started_at timestamp with time zone not null default now(),
  finished_at timestamp with time zone,
  status varchar(20) not null default 'running' check (status in ('running', 'succeeded', 'failed')),
  schools_processed integer not null default 0 check (schools_processed >= 0),
  error_message text
);

create index if not exists teachers_school_id_idx on public.teachers (school_id);
create index if not exists courses_school_subject_active_idx on public.courses (school_id, subject) where is_active;
create index if not exists reviews_user_id_idx on public.reviews (user_id);
create index if not exists reviews_school_id_idx on public.reviews (school_id);
create index if not exists reviews_teacher_id_idx on public.reviews (teacher_id) where teacher_id is not null;
create index if not exists reviews_verified_approved_school_idx
  on public.reviews (school_id, created_at desc)
  where verified and moderation_status = 'approved' and teacher_id is null;
create index if not exists review_criterion_scores_criterion_idx
  on public.review_criterion_scores (criterion, review_id);
create index if not exists events_telegram_id_idx on public.events (telegram_id);
create index if not exists events_name_created_idx on public.events (event_name, created_at desc);
