-- Site leads: a student asks a school to contact them. These tables hold personal data (name, a contact,
-- the exam subject), so they must live ONLY on the Russian server (art. 18(5) of 152-FZ), never in the
-- Irish Supabase project. Apply this migration to the self-hosted Postgres after the migration to a VPS.
create table if not exists public.lead_schools (
  school_id integer primary key references public.schools(id) on delete cascade,
  enabled boolean not null default false,
  legal_name varchar(200) not null default '',
  inn varchar(12) not null default '',
  policy_url varchar(500) not null default '',
  contact_types varchar(60) not null default 'phone,telegram,vk',
  delivery_email varchar(200) not null default '',
  webhook_url varchar(500) not null default '',
  tg_chat_id varchar(40) not null default ''
);

create table if not exists public.leads (
  id integer generated by default as identity primary key,
  school_id integer not null references public.schools(id) on delete cascade,
  name varchar(80) not null,
  contact_type varchar(12) not null check (contact_type in ('phone', 'telegram', 'vk')),
  contact varchar(120) not null,
  contact_hash varchar(64) not null,
  subject varchar(60) not null,
  guardian boolean not null default false,
  consent_version varchar(30) not null,
  consent_at timestamp not null,
  source varchar(30) not null default 'site',
  status varchar(16) not null default 'new' check (status in ('new', 'sent', 'failed', 'withdrawn')),
  attempts integer not null default 0,
  last_error varchar(300) not null default '',
  sent_at timestamp,
  withdraw_hash varchar(64) not null default '',
  created_at timestamp not null default now()
);
create index if not exists leads_school_idx on public.leads (school_id);
create index if not exists leads_hash_idx on public.leads (contact_hash);
create index if not exists leads_status_idx on public.leads (status);
create index if not exists leads_withdraw_idx on public.leads (withdraw_hash);
create index if not exists leads_created_idx on public.leads (created_at);

-- Nobody reads these through the public API: RLS on, no policies, no grants to anon/authenticated.
alter table public.lead_schools enable row level security;
alter table public.leads enable row level security;
revoke all on public.lead_schools, public.leads from anon, authenticated;
grant select, insert, update, delete on public.lead_schools, public.leads to egeshka_bot_app;
grant usage, select on all sequences in schema public to egeshka_bot_app;
