import { decisionFields, priceContext } from './school-content.js?v=21';
import { priceDetails, relativeStrengths } from './comparison.js?v=20';
const $ = (selector) => document.querySelector(selector);
const escape = (value) => String(value).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const number = n => Number(n).toFixed(1).replace('.', ',');
const criteria = {teachers_score:'Преподаватели',practice_score:'Практика и ДЗ',feedback_score:'Проверка работ',curator_score:'Кураторы',platform_score:'Платформа',workload_score:'Нагрузка и темп',organization_score:'Организация обучения'};
const teacherCriteria = {explanation:'Объяснение материала',practice:'Практика и разбор ошибок',feedback:'Обратная связь',tempo:'Темп и нагрузка',communication:'Общение и атмосфера'};
const labels = {'русский':'Русский язык','математика':'Математика','обществознание':'Обществознание','физика':'Физика','химия':'Химия','биология':'Биология','информатика':'Информатика','английский':'Английский язык','история':'История','литература':'Литература','география':'География'};
const quizSubjectKeys = Object.keys(labels).filter(key => key !== 'география');
const dialog = $('#detail-dialog');
let catalog, links = {}, subject = '', expanded = false, mode = 'schools';
function showDialog(html){ $('#dialog-content').innerHTML = html; dialog.showModal();document.querySelector("#dialog-content").scrollTop=0; }
$('.close').onclick = () => dialog.close();
dialog.addEventListener('click', e => { if(e.target === dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close();} });
function methodology(){showDialog(`<div class="method-view"><h2>Как работает рейтинг</h2><p class="method-lead">Две независимые оценки складываются в один понятный результат.</p><div class="rating-formula"><div class="formula-card expert"><small>Редакция ЕГЭшки</small><strong>до 5</strong><span>по открытым данным</span></div><b class="formula-sign">+</b><div class="formula-card students"><small>Ученики</small><strong>до 5</strong><span>по одобренным отзывам</span></div><b class="formula-sign">=</b><div class="formula-card total"><small>Общий рейтинг</small><strong>до 10</strong><span>итоговая оценка</span></div></div><div class="method-note"><strong>★ Предварительная оценка</strong><span>Отзывов учеников пока недостаточно, поэтому показана только редакционная часть, пересчитанная на шкалу 0–10.</span></div><h3>Что входит в оценку ЕГЭшки</h3><div class="weight-grid"><div class="weight-item"><b>24%</b><span>Преподаватели</span></div><div class="weight-item"><b>16%</b><span>Практика</span></div><div class="weight-item"><b>14%</b><span>Проверка работ</span></div><div class="weight-item"><b>14%</b><span>Кураторы</span></div><div class="weight-item"><b>14%</b><span>Организация обучения</span></div><div class="weight-item"><b>10%</b><span>Платформа</span></div><div class="weight-item"><b>8%</b><span>Нагрузка</span></div></div><p class="trust-note"><strong>Организация обучения:</strong> насколько понятны расписание, учебный маршрут, контроль прогресса и правила курса. Стоимость оценивается отдельно.</p><p class="trust-note"><strong>Важно:</strong> результаты учеников, которые публикуют школы, — заявления самих школ. Они не гарантируют такой же результат каждому.</p></div>`);}
$('#compare-method').onclick = methodology;
function renderSchools(){
  let rows = catalog.schools.filter(s => !subject || s.subjects.includes(subject));
  rows.sort($('#sort').value === 'name' ? (a,b)=>a.name.localeCompare(b.name,'ru') : (a,b)=>b.score-a.score);
  $('#catalog-label').textContent = `${subject ? labels[subject] : 'Все предметы'} · ${rows.length} ${rows.length===1?"школа":rows.length<5?"школы":"школ"}`;
  $('#show-more').hidden = expanded || rows.length<=3;
  $('#school-list').innerHTML = rows.slice(0,expanded?rows.length:3).map((s,i)=>`<article class="school-card"><div class="school-card-top"><span class="school-mark ${i%2?'pink-mark':'blue-mark'}">${s.name.startsWith('100')?'100':escape(s.name.slice(0,1))}</span><span class="rank">${$('#sort').value==='rating'?`${i+1} в этом списке`:'Онлайн-школа'}</span></div><h3>${escape(s.name)}</h3>${decisionFields(s)}<div class="card-score"><span>Оценка ЕГЭшки</span><strong>${number(s.score)}<small>/10*</small></strong></div><button class="card-open" data-school="${escape(s.name)}">Подробнее о школе <span>↗</span></button></article>`).join('');
  document.querySelectorAll('[data-school]').forEach(b=>b.onclick=()=>schoolDetails(b.dataset.school));
}
function schoolDetails(name){const s=catalog.schools.find(x=>x.name===name);const top=Object.entries(s.criteria).sort((a,b)=>b[1]-a[1]).slice(0,3);showDialog(`<div class="school-detail"><div class="detail-hero"><div><h2>${escape(s.name)}</h2><p>${escape(s.description)}</p></div><div class="detail-score"><small>Оценка ЕГЭшки</small><strong>${number(s.score)}</strong><span>из 10*</span></div></div><div class="detail-subjects">${s.subjects.map(x=>`<span>${escape(labels[x]||x)}</span>`).join('')}</div><h3>Что особенно хорошо</h3><div class="detail-highlights">${top.map(([key,value])=>`<div><span>${escape(criteria[key])}</span><strong>${number(value)}</strong><i><b style="width:${value*10}%"></b></i></div>`).join('')}</div><div class="detail-grid"><article class="detail-card price"><h3>Сколько стоит</h3><p>${escape(s.price)}</p></article><article class="detail-card format"><h3>Формат</h3><p>${escape(s.format)}</p></article><article class="detail-card strength"><h3>Почему выбирают</h3><p>${escape(s.strengths)}</p></article><article class="detail-card attention"><h3>Что проверить</h3><p>${escape(s.weaknesses)}</p></article></div><div class="detail-footer"><p>* Предварительная редакционная оценка по открытым данным.</p><a class="button blue" href="${escape(s.url)}" target="_blank" rel="noopener">Перейти на сайт школы <span>↗</span></a></div></div>`);}
const siteQuiz={step:0,answers:{}};
const quizSteps=[
 {key:'subject',title:'Какой предмет сдаёшь?',options:()=>quizSubjectKeys.map(value=>[labels[value],value])},
 {key:'budget',title:'Сколько готов тратить в месяц?',options:()=>[['До 3 000 ₽','3000'],['3 000–5 000 ₽','5000'],['5 000–8 000 ₽','8000'],['Больше 8 000 ₽','12000'],['Пока не определился','0']]},
 {key:'level',title:'Как оцениваешь свою базу?',options:()=>[['Начинаю почти с нуля','low'],['Что-то знаю, нужна система','middle'],['База хорошая, хочу усилить результат','high']]},
 {key:'target',title:'На какой результат ориентируешься?',options:()=>[['60+','60'],['70+','70'],['80+','80'],['90+','90']]},
];
const resultPriority=school=>{const a=siteQuiz.answers;if(a.level==='low')return 'curator_score';if(Number(a.target)>=90)return school.criteria.teachers_score>=school.criteria.practice_score?'teachers_score':'practice_score';return Object.keys(criteria).sort((x,y)=>school.criteria[y]-school.criteria[x])[0];};
const resultScore=school=>{const a=siteQuiz.answers,c=school.criteria;let score=school.score*10;if(a.level==='low')score+=c.curator_score*.8+c.feedback_score*.35;if(a.level==='high')score+=c.teachers_score*.45+c.practice_score*.45;if(Number(a.target)>=90)score+=c.teachers_score*.65+c.practice_score*.55;const budget=Number(a.budget),price=Number(school.monthlyPriceFrom);if(budget&&price){if(price<=budget)score+=8;else score-=Math.min(18,(price-budget)/budget*12);}return score;};
const shortPrice=value=>value.length>118?`${value.slice(0,115).trim()}…`:value;
function renderSiteQuiz(){const step=quizSteps[siteQuiz.step];if(!step){const subjectIndex=quizSubjectKeys.indexOf(siteQuiz.answers.subject);const payload=`site_${subjectIndex}_${siteQuiz.answers.budget}_${siteQuiz.answers.level[0]}_${siteQuiz.answers.target}`;const top=catalog.schools.filter(s=>s.subjects.includes(siteQuiz.answers.subject)).sort((a,b)=>resultScore(b)-resultScore(a)).slice(0,3);const cards=top.map((school,index)=>{const best=resultPriority(school);const weakest=Object.keys(criteria).sort((a,b)=>school.criteria[a]-school.criteria[b])[0];return `<article class="quiz-match"><div class="quiz-match-head"><span>${index+1}</span><h3>${escape(school.name)}</h3><strong>${number(school.score)}<small>/10*</small></strong></div><p><b>Почему в списке:</b> ${escape(criteria[best])} — ${number(school.criteria[best])}/10 по редакционной оценке.</p><p><b>Проверь подробнее:</b> критерий «${escape(criteria[weakest])}» и условия конкретного курса.</p><small><b>Ориентир по цене:</b> ${escape(shortPrice(school.price))}</small></article>`;}).join('');showDialog(`<div class="quiz-result"><h2>Предварительно подошли три школы</h2><p>Это первый отбор по предмету, бюджету, базе и цели. Ниже видно, почему каждый вариант попал в список.</p><div class="quiz-matches">${cards}</div><a class="button pink" href="${escape(links.bot)}?start=${payload}" target="_blank" rel="noopener">Уточнить подбор в боте <span>↗</span></a><small>В боте зададим ещё четыре вопроса и пересчитаем порядок. Предмет и бюджет повторно вводить не придётся.</small></div>`);return;}showDialog(`<div class="site-quiz"><div class="quiz-progress"><span>Вопрос ${siteQuiz.step+1} из ${quizSteps.length}</span><i><b style="width:${(siteQuiz.step+1)/quizSteps.length*100}%"></b></i></div><h2>${step.title}</h2><div class="quiz-options">${step.options().map(([label,value])=>`<button data-quiz-value="${escape(value)}">${escape(label)}<span>→</span></button>`).join('')}</div>${siteQuiz.step?'<button class="quiz-back">← Назад</button>':''}</div>`);document.querySelectorAll('[data-quiz-value]').forEach(button=>button.onclick=()=>{siteQuiz.answers[step.key]=button.dataset.quizValue;siteQuiz.step++;renderSiteQuiz();});const back=$('.quiz-back');if(back)back.onclick=()=>{siteQuiz.step--;renderSiteQuiz();};}
$('#quiz-start').onclick=()=>{siteQuiz.step=0;siteQuiz.answers={};renderSiteQuiz();};
function candidates(){return mode==='schools'?catalog.schools:catalog.teachers.filter(t=>t.subject===$('#teacher-subject').value);}
function populateComparison(){const rows=candidates();['left','right'].forEach((side,i)=>{$(`#${side}-select`).innerHTML=rows.map((r,j)=>`<option value="${j}">${escape(r.name)}${mode==='teachers'?` · ${escape(r.school)}`:''}</option>`).join('');$(`#${side}-select`).value=String(Math.min(i,rows.length-1));});renderComparison();}
function renderComparison(changed){const rows=candidates(),l=$('#left-select'),r=$('#right-select');if(l.value===r.value&&rows.length>1){const other=changed==='right'?l:r;other.value=String((Number(other.value)+1)%rows.length);}const left=rows[Number(l.value)],right=rows[Number(r.value)];if(!left||!right){$('#comparison-result').textContent='Для сравнения нужны два преподавателя по этому предмету.';return;}
document.querySelectorAll('#left-select option').forEach(o=>o.disabled=o.value===r.value);document.querySelectorAll('#right-select option').forEach(o=>o.disabled=o.value===l.value);
const row=(title,a,b,cls='')=>`<div class="comparison-row ${cls}"><span>${title}</span><p>${a}</p><p>${b}</p></div>`;
const meter=value=>{const score=Math.max(0,Math.min(10,Number(value)));return `<span class="meter-value">${number(score)}</span><span class="meter meter-segments" aria-hidden="true">${Array.from({length:10},(_,i)=>`<i style="--fill:${Math.max(0,Math.min(1,score-i))*100}%"></i>`).join('')}</span>`;};
let html=row('Шкала 0–10*',escape(left.name),escape(right.name),'column-heads');
html+=row('Общая оценка',`<strong>${number(left.score)}</strong>`,`<strong>${number(right.score)}</strong>`);
if(mode==='schools'){html+=Object.entries(criteria).map(([key,label])=>row(label,meter(left.criteria[key]),meter(right.criteria[key]))).join('');html+='<p class="fine">* Предварительно: по оценкам ЕГЭшки, без отзывов учеников.</p>';}else{
 html+=row('Школа',escape(left.school),escape(right.school));
 html+='<div class="criteria-title"><strong>По оценкам учеников</strong><span>Отдельные критерии · шкала 1–5</span></div>';
 const teacherMetric=(teacher,key)=>Number.isFinite(Number(teacher.criteria?.[key]))?meter(Number(teacher.criteria[key])):'<span class="no-score">Пока нет оценок</span>';
 html+=Object.entries(teacherCriteria).map(([key,label])=>row(label,teacherMetric(left,key),teacherMetric(right,key),'teacher-metric')).join('');
 html+='<p class="fine">Критерии появятся после одобренных отзывов учеников.</p>';
}
if(mode==='schools'){
 const priceCard=school=>{
  const price=priceDetails[school.name];
  if(!price)return `<article class="compare-price-card"><h4>${escape(school.name)}</h4><p>${escape(school.price)}</p>${priceContext(school)}</article>`;
  return `<article class="compare-price-card"><h4>${escape(school.name)}</h4><strong>${escape(price.period)}</strong><dl><div><dt>За весь курс</dt><dd>${escape(price.total)}</dd></div><div><dt>Рассрочка / оплата частями</dt><dd>${escape(price.installment)}</dd></div></dl><p>${escape(price.note)}</p>${priceContext(school)}<a href="${escape(school.url)}" target="_blank" rel="noopener">Проверить тариф на сайте ↗</a></article>`;
 };
 const summaryCard=(school,other)=>{
  const strengths=relativeStrengths(school,other);
  const text=strengths.length?`Выше оценки по критериям: ${strengths.map(key=>criteria[key].toLowerCase()).join(' и ')}.`:'В этой паре нет критериев с более высокой оценкой. Сравни конкретного преподавателя, тариф и формат занятий.';
  return `<article><h4>${escape(school.name)}</h4><p>${escape(text)}</p></article>`;
 };
 html+=`<section class="compare-prices" aria-label="Стоимость подготовки"><h3>Сколько стоит подготовка</h3><p class="compare-price-context">Ориентиры из каталога: пакеты и сроки обучения отличаются.</p><div class="compare-price-grid">${priceCard(left)}${priceCard(right)}</div></section><section class="compare-verdict" aria-label="Краткий вывод"><h3>Что это значит для выбора</h3><div class="compare-verdict-grid">${summaryCard(left,right)}${summaryCard(right,left)}</div><p class="fine">Вывод по редакционным оценкам школы в целом. Небольшая разница баллов не гарантирует лучший результат. «Организация обучения» учитывает ясность расписания, учебного маршрута, контроля прогресса и правил курса; стоимость показана отдельно.</p></section>`;
}else{
 const teacherCard=t=>`<article class="teacher-compare-card"><div><span>${escape(t.school)}</span><strong>${number(t.score)}<small>/10*</small></strong></div><h3>${escape(t.name)}</h3><p>${escape(t.description)}</p><a href="${escape(t.url)}" target="_blank" rel="noopener">Открыть профиль <b>↗</b></a></article>`;
 html+=`<details class="teacher-details"><summary class="comparison-summary">Подробнее о преподавателях</summary><div class="teacher-compare-cards">${teacherCard(left)}${teacherCard(right)}</div></details>`;
}
$('#comparison-result').innerHTML=html;}
$('#left-select').onchange=()=>renderComparison('left');$('#right-select').onchange=()=>renderComparison('right');$('#teacher-subject').onchange=populateComparison;
document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>{mode=b.dataset.mode;document.querySelectorAll('[data-mode]').forEach(x=>{x.classList.toggle('active',x===b);x.setAttribute('aria-pressed',String(x===b));});$('#teacher-subject-wrap').hidden=mode!=='teachers';$('#left-label').textContent=mode==='teachers'?'2. Первый преподаватель':'Первая школа';$('#right-label').textContent=mode==='teachers'?'3. Второй преподаватель':'Вторая школа';populateComparison();});
try{
 const response=await fetch('catalog.json');if(!response.ok)throw new Error('catalog');catalog=await response.json();
 $('#teacher-subject').innerHTML=[...new Set(catalog.teachers.map(t=>t.subject))].sort().map(s=>`<option>${escape(s)}</option>`).join('');
 populateComparison();
 links=await fetch('links.json').then(r=>r.json());$('#channel-link').href=links.channel;$('#review-link').href=links.bot;
 if(new URLSearchParams(location.search).get('start')==='quiz'){$('#quiz-start').click();history.replaceState(null,'',location.pathname);}
}catch(error){console.error(error);}
