"""Export public editorial catalog only; never reads users, reviews or secrets."""
import json
from pathlib import Path
import sys

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from egeshka_bot.db import SCHOOL_REVIEW_SLUGS, SEED, TEACHERS
from egeshka_bot.scoring import BASE_WEIGHTS
from egeshka_bot.subjects import SUBJECTS

schools = []
for row in SEED:
    schools.append({
        'name': row['name'], 'description': row['description'],
        'subjects': row['subjects'].split(','), 'price': row['price_text'],
        'monthlyPriceFrom': row['monthly_price_from'],
        'strengths': row['strengths'], 'weaknesses': row['weaknesses'],
        'format': row['format_text'], 'url': row['official_url'],
        'reviewSlug': SCHOOL_REVIEW_SLUGS[row['name']],
        'criteria': {key: row[key] for key in BASE_WEIGHTS},
        'score': round(sum(row[key] * weight for key, weight in BASE_WEIGHTS.items()), 1),
    })
catalog = {'schools': schools, 'teachers': [
    {'school': t[0], 'name': t[1], 'subject': t[2], 'subjects': t[2].split(' / '), 'description': t[3], 'score': t[4], 'criteria': {}, 'url': t[6]}
    for t in TEACHERS
]}
Path(__file__).with_name('catalog.json').write_text(json.dumps(catalog, ensure_ascii=False, indent=2) + '\n')

labels = {s.lower(): {"Русский": "Русский язык", "Английский": "Английский язык"}.get(s, s) for s in SUBJECTS}
Path(__file__).with_name('subjects.js').write_text('// Generated by export_catalog.py; subject order preserves bot deep links.\nexport const labels = ' + json.dumps(labels, ensure_ascii=False) + ';\nexport const quizSubjectKeys = Object.keys(labels);\nexport const teacherSubjects = teacher => teacher.subjects || [teacher.subject];\n')
