import { decisionFields, schoolContent } from './school-content.js?v=22';
const $ = selector => document.querySelector(selector);
const escape = value => String(value).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const number = n => Number(n).toFixed(1).replace('.', ',');
const criteria = {teachers_score:'Преподаватели',practice_score:'Практика и ДЗ',feedback_score:'Проверка работ',curator_score:'Кураторы',platform_score:'Платформа',workload_score:'Нагрузка и темп',organization_score:'Организация обучения'};
const criterionDetails = [
  ['24%', 'Преподаватели', 'Опыт, профильная квалификация, понятность объяснений и подтверждённые результаты.'],
  ['16%', 'Практика и ДЗ', 'Объём и регулярность заданий, пробники, тренажёры и соответствие формату ЕГЭ.'],
  ['14%', 'Проверка работ', 'Сроки проверки, подробность комментариев и помощь в разборе повторяющихся ошибок.'],
  ['14%', 'Кураторы', 'Доступность наставника, скорость ответов, помощь с вопросами и контроль учебного прогресса.'],
  ['14%', 'Организация обучения', 'Понятность расписания, учебного маршрута, контроля прогресса и правил курса.'],
  ['10%', 'Платформа', 'Стабильность и удобство сервиса, доступ к записям, материалам, статистике и заданиям.'],
  ['8%', 'Нагрузка и темп', 'Интенсивность занятий и домашних работ, возможность совмещать курс со школой и другими предметами.'],
];
const methodologyCriteria = () => criterionDetails.map(([weight, title, description]) => `<article class="weight-item"><b>${weight}</b><span>${title}</span><small>${description}</small></article>`).join('');
const labels = {'русский':'Русский язык','математика':'Математика','обществознание':'Обществознание','физика':'Физика','химия':'Химия','биология':'Биология','информатика':'Информатика','английский':'Английский язык','история':'История','литература':'Литература','география':'География'};
const schoolLogos = {'Умскул':'assets/schools/umskul.svg','100балльный репетитор':'assets/schools/100points.svg','Сотка':'assets/schools/sotka.webp','Фоксфорд':'assets/schools/foxford.ico','Вебиум':'assets/schools/webium.ico','99 Баллов':'assets/schools/99ballov.ico','Турбо ЕГЭ':'assets/schools/turbo.png','ЕГЭLand':'assets/schools/egeland.png','СМИТАП':'assets/schools/smitup.svg','PARTA':'assets/schools/parta.svg','Skysmart':'assets/schools/skysmart.svg','Школково':'assets/schools/shkolkovo.ico'};
const dialog = $('#detail-dialog');
let catalog, links = {bot: 'https://t.me/egeshka_rate_bot'}, subject = '', expanded = false;
const compareSelection = [];

function showDialog(html){$('#dialog-content').innerHTML=html;dialog.showModal();document.querySelector("#dialog-content").scrollTop=0;}
$('.close').onclick=()=>dialog.close();
dialog.addEventListener('click',event=>{if(event.target===dialog){const box=dialog.getBoundingClientRect();if(event.clientX<box.left||event.clientX>box.right||event.clientY<box.top||event.clientY>box.bottom)dialog.close();}});

function teachersForSchool(name){return catalog.teachers.filter(teacher=>teacher.school===name).sort((a,b)=>b.score-a.score||a.name.localeCompare(b.name,'ru'));}
function schoolMark(school,index){const fallback=school.name.startsWith('100')?'100':school.name.slice(0,1);return `<span class="school-mark school-mark-logo ${index%2?'pink-mark':'blue-mark'}" title="${escape(school.name)}"><b>${escape(fallback)}</b><img src="${escape(schoolLogos[school.name])}" alt="" aria-hidden="true"></span>`;}
function teacherWord(count){const mod100=count%100,mod10=count%10;if(mod100>=11&&mod100<=14)return 'преподавателей';if(mod10===1)return 'преподаватель';if(mod10>=2&&mod10<=4)return 'преподавателя';return 'преподавателей';}
function firstSentence(value){const text=String(value||'').trim();const match=text.match(/^.*?[.!?](?:\s|$)/);return (match?match[0]:text).trim();}
function subjectSummary(subjects){return subjects.map(item=>labels[item]||item).join(', ');}
function teacherScale(score){return `<span class="teacher-scale" aria-label="Оценка ${number(score)} из 10">${Array.from({length:10},(_,index)=>{const fill=Math.max(0,Math.min(1,Number(score)-index))*100;return `<i style="--fill:${fill}%"></i>`;}).join('')}</span>`;}
function teacherCard(teacher){const more=teacher.description.length>155?'<button class="teacher-more" aria-expanded="false">Читать полностью <span>↓</span></button>':'';return `<article class="teacher-profile" data-teacher-subject="${escape(teacher.subject)}"><div class="teacher-profile-head"><span class="teacher-monogram">${escape(teacher.name.trim().slice(0,1))}</span><div><p>${escape(teacher.subject)}</p><h3>${escape(teacher.name)}</h3></div><strong>${number(teacher.score)}</strong></div>${teacherScale(teacher.score)}<p class="teacher-description">${escape(teacher.description)}</p>${more}<a href="${escape(teacher.url)}" target="_blank" rel="noopener">Подробнее о преподавателе <span>↗</span></a></article>`;}
function schoolTeachers(name){const teachers=teachersForSchool(name);const subjects=[...new Set(teachers.map(teacher=>teacher.subject))].sort((a,b)=>a.localeCompare(b,'ru'));showDialog(`<div class="teacher-directory"><div class="teacher-directory-head"><div><p class="teacher-kicker">Команда школы</p><h2>${escape(name)}</h2><p>${teachers.length} ${teacherWord(teachers.length)} в каталоге ЕГЭшки. Выбери предмет и сравни оценки.</p></div><div class="teacher-directory-count"><strong>${teachers.length}</strong><span>карточек</span></div></div><div class="teacher-subjects" role="group" aria-label="Фильтр преподавателей по предмету"><button class="active" data-teacher-filter="" aria-pressed="true">Все</button>${subjects.map(item=>`<button data-teacher-filter="${escape(item)}" aria-pressed="false">${escape(item)}</button>`).join('')}</div><p class="teacher-result" aria-live="polite">Показаны все преподаватели</p><div class="teacher-grid">${teachers.map(teacherCard).join('')}</div><p class="teacher-note">Оценки предварительные и собраны по открытым данным. Результаты учеников в описаниях опубликованы школами или преподавателями.</p></div>`);const cards=[...document.querySelectorAll('[data-teacher-subject]')];const result=$('.teacher-result');document.querySelectorAll('[data-teacher-filter]').forEach(button=>button.onclick=()=>{const value=button.dataset.teacherFilter;let visible=0;document.querySelectorAll('[data-teacher-filter]').forEach(item=>{const active=item===button;item.classList.toggle('active',active);item.setAttribute('aria-pressed',String(active));});cards.forEach(card=>{const show=!value||card.dataset.teacherSubject===value;card.hidden=!show;if(show)visible++;});result.textContent=value?`${value} · ${visible} ${teacherWord(visible)}`:'Показаны все преподаватели';});document.querySelectorAll('.teacher-more').forEach(button=>button.onclick=()=>{const card=button.closest('.teacher-profile');const expanded=card.classList.toggle('description-open');button.setAttribute('aria-expanded',String(expanded));button.innerHTML=expanded?'Свернуть <span>↑</span>':'Читать полностью <span>↓</span>';});}

function methodology(){showDialog(`<div class="method-view"><h2>Как работает рейтинг</h2><p class="method-lead">Две независимые оценки складываются в один понятный результат.</p><div class="rating-formula"><div class="formula-card expert"><small>Редакция ЕГЭшки</small><strong>до 5</strong><span>по открытым данным</span></div><b class="formula-sign">+</b><div class="formula-card students"><small>Ученики</small><strong>до 5</strong><span>по одобренным отзывам</span></div><b class="formula-sign">=</b><div class="formula-card total"><small>Общий рейтинг</small><strong>до 10</strong><span>итоговая оценка</span></div></div><div class="method-note"><strong>★ Предварительная оценка</strong><span>Отзывов учеников пока недостаточно, поэтому показана только редакционная часть, пересчитанная на шкалу 0–10.</span></div><h3>Что входит в оценку ЕГЭшки</h3><div class="weight-grid">${methodologyCriteria()}</div><p class="trust-note"><strong>Стоимость не влияет на балл:</strong> цены и тарифы показаны отдельно, потому что один и тот же бюджет может быть приемлемым для одного ученика и недоступным для другого.</p><p class="trust-note"><strong>Важно:</strong> результаты учеников, которые публикуют школы, — заявления самих школ. Они не гарантируют такой же результат каждому.</p></div>`);}

function schoolDetails(name){const school=catalog.schools.find(item=>item.name===name);const top=Object.entries(school.criteria).sort((a,b)=>b[1]-a[1]).slice(0,3);const teacherCount=teachersForSchool(name).length;const reviewUrl=`${links.bot}?start=review_${school.reviewSlug}`;const caution=schoolContent[name]?.caution||school.weaknesses;showDialog(`<div class="school-detail detail-simple"><div class="detail-hero"><div><h2>${escape(school.name)}</h2><p>${escape(school.description)}</p></div><div class="detail-score"><small>Оценка ЕГЭшки</small><strong>${number(school.score)}</strong><span>из 10*</span></div></div><div class="detail-subject-line"><strong>${school.subjects.length} ${school.subjects.length===1?'предмет':'предметов'}</strong><span>${escape(subjectSummary(school.subjects))}</span></div><section class="detail-facts" aria-label="Основные условия"><article><small>Стоимость</small><p>${escape(firstSentence(school.price))}</p></article><article><small>Формат</small><p>${escape(firstSentence(school.format))}</p></article></section><div class="detail-strength-line"><span>Сильные стороны</span><div>${top.map(([key,value])=>`<b>${escape(criteria[key])}<em>${number(value)}</em></b>`).join('')}</div></div><details class="detail-more"><summary>Что важно перед выбором <span aria-hidden="true">+</span></summary><p class="detail-caution"><strong>Что учесть</strong>${escape(caution)}</p><div class="detail-more-grid"><article><h3>Почему выбирают</h3><p>${escape(school.strengths)}</p></article><article><h3>Что проверить</h3><p>${escape(school.weaknesses)}</p></article></div></details><div class="detail-primary-action"><button data-school-teachers="${escape(name)}"><span><small>Команда школы</small><strong>${teacherCount} ${teacherWord(teacherCount)}</strong></span><b>Посмотреть преподавателей <i>→</i></b></button></div><div class="detail-secondary-actions"><a href="${escape(reviewUrl)}" target="_blank" rel="noopener">Оставить отзыв о школе <span>↗</span></a><a href="${escape(school.url)}" target="_blank" rel="noopener">Сайт школы <span>↗</span></a></div><p class="detail-note">* Предварительная редакционная оценка по открытым данным.</p></div>`);document.querySelector('[data-school-teachers]').onclick=event=>schoolTeachers(event.currentTarget.dataset.schoolTeachers);}

function comparisonUrl(){const params=new URLSearchParams({compareLeft:compareSelection[0],compareRight:compareSelection[1]});return `index.html?${params.toString()}#compare`;}
function renderCompareTray(){let tray=$('#compare-tray');if(!compareSelection.length){tray?.remove();return;}if(!tray){tray=document.createElement('aside');tray.id='compare-tray';tray.className='compare-tray';tray.setAttribute('aria-live','polite');document.body.append(tray);}const ready=compareSelection.length===2;tray.innerHTML=`<div class="compare-tray-copy"><small>${ready?'Готово к сравнению':'Выбери ещё одну школу'}</small><strong>${compareSelection.map(escape).join(' <span>+</span> ')}</strong></div><div class="compare-tray-actions"><button type="button" data-clear-compare>Сбросить</button>${ready?`<a href="${comparisonUrl()}">Сравнить <span>↗</span></a>`:''}</div>`;tray.querySelector('[data-clear-compare]').onclick=()=>{compareSelection.splice(0);syncCompareControls();};}
function syncCompareControls(){document.querySelectorAll('[data-compare-school]').forEach(button=>{const selected=compareSelection.includes(button.dataset.compareSchool);button.classList.toggle('selected',selected);button.setAttribute('aria-pressed',String(selected));button.textContent=selected?'Выбрано ✓':'+ К сравнению';});renderCompareTray();}
function toggleCompare(name){const index=compareSelection.indexOf(name);if(index>=0)compareSelection.splice(index,1);else{if(compareSelection.length===2)compareSelection.shift();compareSelection.push(name);}syncCompareControls();}

function renderSchools(){let rows=catalog.schools.filter(school=>!subject||school.subjects.includes(subject));rows.sort($('#sort').value==='name'?(a,b)=>a.name.localeCompare(b.name,'ru'):(a,b)=>b.score-a.score);$('#catalog-label').textContent=`${subject?labels[subject]:'Все предметы'} · ${rows.length} ${rows.length===1?'школа':rows.length<5?'школы':'школ'}`;$('#show-more').hidden=expanded||rows.length<=6;$('#school-list').innerHTML=rows.slice(0,expanded?rows.length:6).map((school,index)=>{const teacherCount=teachersForSchool(school.name).length;const selected=compareSelection.includes(school.name);return `<article class="school-card"><div class="school-card-top">${schoolMark(school,index)}<div class="school-card-meta"><span class="rank">${$('#sort').value==='rating'?`${index+1} место`:'Онлайн-школа'}</span><button class="card-compare${selected?' selected':''}" type="button" data-compare-school="${escape(school.name)}" aria-pressed="${selected}">${selected?'Выбрано ✓':'+ К сравнению'}</button></div></div><h3>${escape(school.name)}</h3>${decisionFields(school)}<div class="card-score"><span>Оценка ЕГЭшки</span><strong>${number(school.score)}<small>/10*</small></strong></div><div class="school-card-actions"><button class="card-open" data-school="${escape(school.name)}">О школе <span>↗</span></button><button class="card-teachers" data-teachers="${escape(school.name)}">Преподаватели <span>${teacherCount}</span></button></div></article>`;}).join('');document.querySelectorAll('.school-mark-logo img').forEach(image=>image.addEventListener('error',()=>image.remove(),{once:true}));document.querySelectorAll('[data-school]').forEach(button=>button.onclick=()=>schoolDetails(button.dataset.school));document.querySelectorAll('[data-teachers]').forEach(button=>button.onclick=()=>schoolTeachers(button.dataset.teachers));document.querySelectorAll('[data-compare-school]').forEach(button=>button.onclick=()=>toggleCompare(button.dataset.compareSchool));}

try{const [catalogResponse,linksResponse]=await Promise.all([fetch('catalog.json'),fetch('links.json')]);if(!catalogResponse.ok)throw new Error('catalog');catalog=await catalogResponse.json();if(linksResponse.ok)links=await linksResponse.json();$('#subject-list').innerHTML=[['','Все предметы'],...Object.entries(labels)].map(([value,label])=>`<button class="subject ${value===''?'active':''}" data-subject="${value}" aria-pressed="${value===''}">${label}</button>`).join('');document.querySelectorAll('[data-subject]').forEach(button=>button.onclick=()=>{subject=button.dataset.subject;expanded=false;document.querySelectorAll('[data-subject]').forEach(item=>{item.classList.toggle('active',item===button);item.setAttribute('aria-pressed',String(item===button));});renderSchools();});$('#sort').onchange=renderSchools;$('#show-more').onclick=()=>{expanded=true;renderSchools();};$('#methodology').onclick=methodology;renderSchools();}catch(error){$('#school-list').innerHTML='<p>Не удалось загрузить рейтинг. Обнови страницу, чтобы попробовать ещё раз.</p>';console.error(error);}
