import { decisionFields, priceContext, schoolContent, schoolFilters } from './school-content.js?v=28';
import { applyLiveRatings, ratingBreakdown, ratingMark, teacherRatingLabel } from './supabase-client.js?v=4';
const $ = selector => document.querySelector(selector);
const escape = value => String(value).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const number = n => Number(n).toFixed(1).replace('.', ',');
const criteria = {teachers_score:'Преподаватели',practice_score:'Практика и ДЗ',feedback_score:'Проверка работ',curator_score:'Кураторы',platform_score:'Платформа',workload_score:'Нагрузка и темп',organization_score:'Организация обучения'};
const teacherCriteria = {explanation:'Объяснение материала',practice:'Практика и разбор ошибок',atmosphere:'Атмосфера и вовлечённость',structure:'Структура и темп занятий',exam_value:'Польза для экзамена'};
const criterionDetails = [
  ['24%', 'Преподаватели', 'Опыт, профильная квалификация, понятность объяснений и подтверждённые результаты.'],
  ['16%', 'Практика и ДЗ', 'Объём и регулярность заданий, пробники, тренажёры и соответствие формату ЕГЭ.'],
  ['14%', 'Проверка работ', 'Сроки проверки, подробность комментариев и помощь в разборе повторяющихся ошибок.'],
  ['14%', 'Кураторы', 'Доступность наставника, скорость ответов, помощь с вопросами и контроль учебного прогресса.'],
  ['14%', 'Организация обучения', 'Понятность расписания, учебного маршрута, контроля прогресса и правил курса.'],
  ['10%', 'Платформа', 'Стабильность и удобство сервиса, доступ к записям, материалам, статистике и заданиям.'],
  ['8%', 'Нагрузка и темп', 'Интенсивность занятий и домашних работ, возможность совмещать курс со школой и другими предметами.'],
];
const methodologyCriteria = () => criterionDetails.map(([weight, title, description]) => `<article class="weight-item"><b>${weight}</b><span>${title}</span><small>${description}</small></article>`).join('');
import { labels, quizSubjectKeys, teacherSubjects } from './subjects.js?v=1';
const schoolLogos = {'Умскул':'assets/schools/umskul.svg','100балльный репетитор':'assets/schools/100points.svg','Сотка':'assets/schools/sotka.webp','Фоксфорд':'assets/schools/foxford.ico','Вебиум':'assets/schools/webium.ico','99 Баллов':'assets/schools/99ballov.ico','Турбо ЕГЭ':'assets/schools/turbo.png','ЕГЭLand':'assets/schools/egeland.png','СМИТАП':'assets/schools/smitup.svg','PARTA':'assets/schools/parta.svg','Skysmart':'assets/schools/skysmart.svg','Школково':'assets/schools/shkolkovo.ico','ЕГЭ Налегке':'assets/schools/egenalegke.png','StudyCats':'assets/schools/studycats.png','NeoFamily':'assets/schools/neofamily.ico','Морозилка':'assets/schools/morozilka.png','Инсперия':'assets/schools/insperia.svg'};
const dialog = $('#detail-dialog');
const fromQuiz = new URLSearchParams(location.search).get('from') === 'quiz';
const quizReturn = '<a class="quiz-return" href="/?resume=quiz">← Вернуться к подбору</a>';
if(fromQuiz)document.querySelector('main').insertAdjacentHTML('afterbegin',quizReturn);
let catalog, links = {bot: 'https://t.me/egematch_bot'}, subject = '', expanded = false;
const compareSelection = [];
const filterState = {budget:'',lessons:'',curator:false,multiSubject:false};

function detailUrl(params){const url=new URL(location.pathname,location.origin);Object.entries(params).forEach(([key,value])=>url.searchParams.set(key,value));return url;}
function setDetailRoute(params,push=true){const url=new URL(location.href);url.searchParams.delete('school');url.searchParams.delete('teacher');url.searchParams.delete('teacherSchool');Object.entries(params).forEach(([key,value])=>url.searchParams.set(key,value));history[push?'pushState':'replaceState']({detail:true},'',`${url.pathname}${url.search}`);}
function clearDetailRoute(){const params=new URLSearchParams(location.search);if(!params.has('school')&&!params.has('teacher'))return;params.delete('school');params.delete('teacher');params.delete('teacherSchool');const next=`${location.pathname}${params.size?`?${params}`:''}`;history.replaceState(null,'',next);}
function showDialog(html,route=null,push=true){$('#dialog-content').innerHTML=(fromQuiz?quizReturn:'')+html;if(!dialog.open)dialog.showModal();document.querySelector("#dialog-content").scrollTop=0;if(route)setDetailRoute(route,push);}
$('.close').onclick=()=>dialog.close();
dialog.addEventListener('click',event=>{if(event.target===dialog){const box=dialog.getBoundingClientRect();if(event.clientX<box.left||event.clientX>box.right||event.clientY<box.top||event.clientY>box.bottom)dialog.close();}});
dialog.addEventListener('close',clearDetailRoute);
window.addEventListener('popstate',()=>{const params=new URLSearchParams(location.search);if(params.has('school')||params.has('teacher'))openDetailFromUrl(false);else if(dialog.open)dialog.close();});

function teachersForSchool(name){return catalog.teachers.filter(teacher=>teacher.school===name).sort((a,b)=>(b.studentScore??-1)-(a.studentScore??-1)||a.name.localeCompare(b.name,'ru'));}
function schoolMark(school,index){const fallback=school.name.startsWith('100')?'100':school.name.slice(0,1);return `<span class="school-mark school-mark-logo ${index%2?'pink-mark':'blue-mark'}" title="${escape(school.name)}"><b>${escape(fallback)}</b><img src="${escape(schoolLogos[school.name])}" alt="" aria-hidden="true"></span>`;}
function teacherWord(count){const mod100=count%100,mod10=count%10;if(mod100>=11&&mod100<=14)return 'преподавателей';if(mod10===1)return 'преподаватель';if(mod10>=2&&mod10<=4)return 'преподавателя';return 'преподавателей';}
function subjectWord(count){const mod100=count%100,mod10=count%10;if(mod100>=11&&mod100<=14)return 'предметов';if(mod10===1)return 'предмет';if(mod10>=2&&mod10<=4)return 'предмета';return 'предметов';}
function firstSentence(value){const text=String(value||'').trim();const match=text.match(/^.*?[.!?](?:\s|$)/);return (match?match[0]:text).trim();}
function subjectSummary(subjects){return subjects.map(item=>labels[item]||item).join(', ');}
async function copyShareLink(button,params){const shareSchool=params.school&&!params.teacher?catalog.schools.find(item=>item.name===params.school):null;const url=shareSchool?new URL(`/schools/${shareSchool.reviewSlug}`,location.origin).href:detailUrl(params).href;try{await navigator.clipboard.writeText(url);button.dataset.originalLabel||=(button.textContent.trim());button.textContent='Ссылка скопирована ✓';setTimeout(()=>button.textContent=button.dataset.originalLabel,1800);}catch{window.prompt('Скопируй ссылку на карточку',url);}}
function teacherScale(score){if(score==null)return '<p class="teacher-rating-pending">Оценка учеников формируется</p>';return `<span class="teacher-scale" aria-label="Оценка ${number(score)} из 10">${Array.from({length:10},(_,index)=>{const fill=Math.max(0,Math.min(1,Number(score)-index))*100;return `<i style="--fill:${fill}%"></i>`;}).join('')}</span>`;}
function teacherCard(teacher){return `<article class="teacher-profile" data-teacher-subject="${escape(teacherSubjects(teacher).join('|'))}" data-teacher-name="${escape(teacher.name)}"><div class="teacher-profile-head"><span class="teacher-monogram">${escape(teacher.name.trim().slice(0,1))}</span><div><p>${escape(teacher.subject)}</p><h3>${escape(teacher.name)}</h3></div><strong class="teacher-card-score">${escape(teacherRatingLabel(teacher))}</strong></div>${teacherScale(teacher.studentScore)}<p class="teacher-description">${escape(teacher.description)}</p><div class="teacher-card-links"><button type="button" class="teacher-open" data-open-teacher="${escape(teacher.name)}" data-open-school="${escape(teacher.school)}">Открыть карточку <span>→</span></button><button type="button" data-share-teacher="${escape(teacher.name)}" data-share-school="${escape(teacher.school)}">Поделиться <span>↗</span></button></div></article>`;}
function teacherCriteriaRows(teacher){return Object.entries(teacherCriteria).map(([key,label])=>{const raw=teacher.criteria?.[key],value=Number(raw);const hasValue=raw!=null&&Number.isFinite(value);return `<div class="teacher-detail-criterion"><span>${escape(label)}</span>${hasValue?`<strong>${number(value)}<small>/10</small></strong><i aria-hidden="true"><b style="width:${Math.max(0,Math.min(100,value/10*100))}%"></b></i>`:'<em>Пока нет оценки</em>'}</div>`;}).join('');}
function teacherDetails(schoolName,teacherName,options={}){const teacher=catalog.teachers.find(item=>item.school===schoolName&&item.name===teacherName);if(!teacher)return;const subjects=teacherSubjects(teacher);const hasCriteria=Object.values(teacher.criteria||{}).some(value=>value!=null&&Number.isFinite(Number(value)));const score=teacher.studentScore==null?'—':number(teacher.studentScore);const scoreNote=teacher.studentScore==null?'Нужно 3 отзыва':`из 10${teacher.isPreliminary?'*':''}`;showDialog(`<div class="teacher-detail"><button type="button" class="teacher-detail-back">← Все преподаватели школы</button><header class="teacher-detail-head"><div><p class="teacher-kicker">${escape(schoolName)}</p><h2>${escape(teacher.name)}</h2><p>${escape(subjects.join(' · ')||teacher.subject)}</p></div><div class="teacher-detail-score"><small>Оценка учеников</small><strong>${score}</strong><span>${scoreNote}</span></div></header><p class="teacher-detail-description">${escape(teacher.description)}</p><section class="teacher-detail-ratings" aria-label="Оценки преподавателя по критериям"><div class="teacher-detail-ratings-head"><h3>Оценки учеников</h3><p>${hasCriteria?`${teacher.verifiedReviewCount} подтверждённых отзывов`:'Появятся после 3 подтверждённых отзывов'}</p></div>${teacherCriteriaRows(teacher)}</section><div class="teacher-detail-actions"><a class="button blue" href="${escape(teacher.url)}" target="_blank" rel="noopener">Перейти в профиль преподавателя <span>↗</span></a><button type="button" data-share-teacher="${escape(teacher.name)}" data-share-school="${escape(teacher.school)}">Поделиться карточкой <span>↗</span></button></div>${teacher.studentScore!=null&&teacher.isPreliminary?'<p class="teacher-note">* Предварительная оценка: собрано меньше 10 подтверждённых отзывов.</p>':''}</div>`,{teacher:teacher.name,teacherSchool:teacher.school},options.push!==false);$('.teacher-detail-back').onclick=()=>schoolTeachers(schoolName,'',{push:false});document.querySelector('[data-share-teacher]').onclick=event=>copyShareLink(event.currentTarget,{teacher:event.currentTarget.dataset.shareTeacher,teacherSchool:event.currentTarget.dataset.shareSchool});}
function schoolTeachers(name,targetTeacher='',options={}){if(targetTeacher){teacherDetails(name,targetTeacher,options);return;}const teachers=teachersForSchool(name);const subjects=[...new Set(teachers.flatMap(teacherSubjects))].sort((a,b)=>a.localeCompare(b,'ru'));showDialog(`<div class="teacher-directory"><div class="teacher-directory-head"><div><p class="teacher-kicker">Команда школы</p><h2>${escape(name)}</h2><p>Выбери предмет и открой карточку преподавателя с описанием и оценками.</p></div><div class="teacher-directory-count" aria-label="${teachers.length} ${teacherWord(teachers.length)}"><strong>${teachers.length}</strong><span>${teacherWord(teachers.length)}</span></div></div><div class="teacher-subjects" role="group" aria-label="Фильтр преподавателей по предмету"><button class="active" data-teacher-filter="" aria-pressed="true">Все</button>${subjects.map(item=>`<button data-teacher-filter="${escape(item)}" aria-pressed="false">${escape(item)}</button>`).join('')}</div><p class="teacher-result" aria-live="polite">Показаны все преподаватели</p><div class="teacher-grid">${teachers.map(teacherCard).join('')}</div><p class="teacher-note">Общие оценки предварительные и собраны по открытым данным. Оценки по критериям формируются из подтверждённых отзывов.</p></div>`,null,options.push!==false);const cards=[...document.querySelectorAll('[data-teacher-subject]')];const result=$('.teacher-result');document.querySelectorAll('[data-teacher-filter]').forEach(button=>button.onclick=()=>{const value=button.dataset.teacherFilter;let visible=0;document.querySelectorAll('[data-teacher-filter]').forEach(item=>{const active=item===button;item.classList.toggle('active',active);item.setAttribute('aria-pressed',String(active));});cards.forEach(card=>{const show=!value||card.dataset.teacherSubject.split('|').includes(value);card.hidden=!show;if(show)visible++;});result.textContent=value?`${value} · ${visible} ${teacherWord(visible)}`:'Показаны все преподаватели';});document.querySelectorAll('[data-open-teacher]').forEach(button=>button.onclick=()=>teacherDetails(button.dataset.openSchool,button.dataset.openTeacher));document.querySelectorAll('[data-share-teacher]').forEach(button=>button.onclick=()=>copyShareLink(button,{teacher:button.dataset.shareTeacher,teacherSchool:button.dataset.shareSchool}));}

function methodology(){showDialog(`<div class="method-view"><h2>Как работает рейтинг</h2><p class="method-lead">Одна шкала 0–10 для школ и преподавателей, но разный способ расчёта.</p><section class="method-model school-model"><div class="method-model-title"><span>Школа</span></div><div class="rating-formula"><div class="formula-card expert"><small>Редакция</small><strong>до 10</strong><span>по открытым данным</span></div><b class="formula-sign">→</b><div class="formula-card students"><small>Ученики</small><strong>до 10</strong><span>вес растёт с числом отзывов</span></div><b class="formula-sign">=</b><div class="formula-card total"><small>Итог школы</small><strong>до 10</strong><span>общая оценка</span></div></div></section><section class="method-model teacher-model"><div class="teacher-model-score"><small>Преподаватель</small><strong>до 10</strong><span>только оценки учеников</span></div><div class="teacher-model-rule"><strong>Ученик оценивает 5 критериев</strong><span>Среднее из них — итоговая оценка преподавателя. Показываем, когда набирается вес трёх подтверждённых отзывов (неподтверждённые весят меньше). До 10 отзывов ставим *.</span></div></section><h3>Что входит в редакционную оценку школы</h3><div class="weight-grid">${methodologyCriteria()}</div><p class="trust-note"><strong>Стоимость не влияет на балл:</strong> цены и тарифы показаны отдельно, потому что один и тот же бюджет может быть приемлемым для одного ученика и недоступным для другого.</p><p class="trust-note"><strong>Важно:</strong> результаты учеников, которые публикуют школы, — заявления самих школ. Они не гарантируют такой же результат каждому.</p><a class="method-full-link" href="/methodology">Открыть полную методологию →</a></div>`);}

function schoolDetails(name,options={}){const school=catalog.schools.find(item=>item.name===name);if(!school)return;const ordered=Object.entries(school.criteria).sort((a,b)=>b[1]-a[1]);const top=ordered.slice(0,3);const bottom=ordered.slice(-3).reverse();const teacherCount=teachersForSchool(name).length;const reviewUrl=`${links.bot}?start=review_${school.reviewSlug}`;const caution=schoolContent[name]?.caution||school.weaknesses;showDialog(`<div class="school-detail detail-simple"><div class="detail-hero"><div><h2>${escape(school.name)}</h2><p>${escape(school.description)}</p></div><div class="detail-score"><small>Оценка ЕГЭ Мэтча</small><strong>${number(school.score)}</strong><span>из 10${ratingMark(school)}</span></div></div>${ratingBreakdown(school)}<div class="detail-subject-line"><strong>${school.subjects.length} ${subjectWord(school.subjects.length)}</strong><span>${escape(subjectSummary(school.subjects))}</span></div><section class="detail-facts" aria-label="Основные условия"><article><small>Стоимость</small><p>${escape(firstSentence(school.price))}</p>${priceContext(school)}</article><article><small>Формат</small><p>${escape(firstSentence(school.format))}</p></article></section><div class="detail-strength-line"><span>Сильные стороны</span><div>${top.map(([key,value])=>`<b>${escape(criteria[key])}<em>${number(value)}</em></b>`).join('')}</div></div><div class="detail-weakness-line"><span>Слабые стороны</span><div>${bottom.map(([key,value])=>`<b>${escape(criteria[key])}<em>${number(value)}</em></b>`).join('')}</div></div><details class="detail-more"><summary>Что важно перед выбором <span aria-hidden="true">+</span></summary><p class="detail-caution"><strong>Что учесть</strong>${escape(caution)}</p><div class="detail-more-grid"><article><h3>Почему выбирают</h3><p>${escape(school.strengths)}</p></article><article><h3>Что проверить</h3><p>${escape(school.weaknesses)}</p></article></div></details><div class="detail-primary-action"><button data-school-teachers="${escape(name)}"><span><small>Команда школы</small><strong>${teacherCount} ${teacherWord(teacherCount)}</strong></span><b>Посмотреть преподавателей <i>→</i></b></button></div><div class="detail-secondary-actions"><a href="${escape(reviewUrl)}" target="_blank" rel="noopener">Оставить отзыв о школе <span>↗</span></a><button type="button" data-share-current-school>Поделиться карточкой <span>↗</span></button><a href="${escape(school.url)}" target="_blank" rel="noopener">Сайт школы <span>↗</span></a></div>${school.isPreliminary?'<p class="detail-note">* Предварительная оценка: подтверждённых отзывов пока недостаточно.</p>':''}</div>`,{school:name},options.push!==false);document.querySelector('[data-school-teachers]').onclick=event=>schoolTeachers(event.currentTarget.dataset.schoolTeachers);document.querySelector('[data-share-current-school]').onclick=event=>copyShareLink(event.currentTarget,{school:name});}

function openDetailFromUrl(push=false){if(!catalog)return;const params=new URLSearchParams(location.search);const teacher=params.get('teacher'),teacherSchool=params.get('teacherSchool'),school=params.get('school');if(teacher&&teacherSchool){schoolTeachers(teacherSchool,teacher,{push});return;}if(school)schoolDetails(school,{push});}

function comparisonUrl(){const params=new URLSearchParams({compareLeft:compareSelection[0],compareRight:compareSelection[1]});return `/?${params.toString()}#compare`;}
function renderCompareTray(){let tray=$('#compare-tray');if(!compareSelection.length){tray?.remove();return;}if(!tray){tray=document.createElement('aside');tray.id='compare-tray';tray.className='compare-tray';tray.setAttribute('aria-live','polite');document.body.append(tray);}const ready=compareSelection.length===2;tray.innerHTML=`<div class="compare-tray-copy"><small>${ready?'Готово к сравнению':'Выбери ещё одну школу'}</small><strong>${compareSelection.map(escape).join(' <span>+</span> ')}</strong></div><div class="compare-tray-actions"><button type="button" data-clear-compare>Сбросить</button>${ready?`<a href="${comparisonUrl()}">Сравнить <span>→</span></a>`:''}</div>`;tray.querySelector('[data-clear-compare]').onclick=()=>{compareSelection.splice(0);syncCompareControls();};}
function syncCompareControls(){document.querySelectorAll('[data-compare-school]').forEach(button=>{const selected=compareSelection.includes(button.dataset.compareSchool);button.classList.toggle('selected',selected);button.setAttribute('aria-pressed',String(selected));button.innerHTML=`<span aria-hidden="true">${selected?'✓':'+'}</span>${selected?'В сравнении':'К сравнению'}`;});renderCompareTray();}
function toggleCompare(name){const index=compareSelection.indexOf(name);if(index>=0)compareSelection.splice(index,1);else{if(compareSelection.length===2)compareSelection.shift();compareSelection.push(name);}syncCompareControls();}

function schoolMatchesFilters(school){const meta=schoolFilters[school.name]||{};if(subject&&!school.subjects.includes(subject))return false;if(filterState.budget&&(!Number.isFinite(meta.priceFrom)||meta.priceFrom>Number(filterState.budget)))return false;if(filterState.lessons&&!meta.lessons?.includes(filterState.lessons))return false;if(filterState.curator&&!meta.curator)return false;if(filterState.multiSubject&&school.subjects.length<5)return false;return true;}
function filtersActive(){return Boolean(subject||filterState.budget||filterState.lessons||filterState.curator||filterState.multiSubject);}
function updateFilterUrl(){const url=new URL(location.href);const values={subject,budget:filterState.budget,lessons:filterState.lessons,curator:filterState.curator?'1':'',multiSubject:filterState.multiSubject?'1':'',sort:$('#sort').value==='name'?'name':''};Object.entries(values).forEach(([key,value])=>value?url.searchParams.set(key,value):url.searchParams.delete(key));history.replaceState(history.state,'',`${url.pathname}${url.search}`);}
function syncFilterControls(){$('#filter-budget').value=filterState.budget;$('#filter-lessons').value=filterState.lessons;$('#filter-curator').checked=filterState.curator;$('#filter-multisubject').checked=filterState.multiSubject;$('#reset-filters').hidden=!filtersActive();}
function renderSchools(){let rows=catalog.schools.filter(schoolMatchesFilters);rows.sort($('#sort').value==='name'?(a,b)=>a.name.localeCompare(b.name,'ru'):(a,b)=>b.score-a.score);$('#catalog-label').textContent=`${subject?labels[subject]:'Все предметы'} · ${rows.length} ${rows.length===1?'школа':rows.length<5?'школы':'школ'}`;$('#scope-note').textContent=subject?`Показаны школы с предметом «${labels[subject]}». Баллы — общая оценка школы, а не отдельного курса.`:'Показаны все школы. Баллы — общая оценка школы, а не отдельного курса.';$('#show-more').hidden=expanded||rows.length<=6;syncFilterControls();if(!rows.length){$('#school-list').innerHTML='<div class="catalog-empty"><h3>Таких вариантов пока нет</h3><p>Попробуй увеличить бюджет или убрать один из дополнительных фильтров.</p><button type="button" data-reset-empty>Сбросить фильтры</button></div>';document.querySelector('[data-reset-empty]').onclick=resetFilters;return;}$('#school-list').innerHTML=rows.slice(0,expanded?rows.length:6).map((school,index)=>{const teacherCount=teachersForSchool(school.name).length;const selected=compareSelection.includes(school.name);return `<article class="school-card"><div class="school-card-top">${schoolMark(school,index)}<span class="rank">${$('#sort').value==='rating'?`${index+1} место`:'Онлайн-школа'}</span></div><h3>${escape(school.name)}</h3>${decisionFields(school)}<div class="card-score"><span>Оценка ЕГЭ Мэтча</span><strong>${number(school.score)}<small>/10${ratingMark(school)}</small></strong></div><div class="school-card-actions"><button class="card-open" data-school="${escape(school.name)}">О школе <span>→</span></button><button class="card-teachers" data-teachers="${escape(school.name)}">Преподаватели <span>${teacherCount}</span></button><button class="card-compare${selected?' selected':''}" type="button" data-compare-school="${escape(school.name)}" aria-pressed="${selected}"><span aria-hidden="true">${selected?'✓':'+'}</span>${selected?'В сравнении':'К сравнению'}</button></div></article>`;}).join('');document.querySelectorAll('.school-mark-logo img').forEach(image=>image.addEventListener('error',()=>image.remove(),{once:true}));document.querySelectorAll('[data-school]').forEach(button=>button.onclick=()=>schoolDetails(button.dataset.school));document.querySelectorAll('[data-teachers]').forEach(button=>button.onclick=()=>schoolTeachers(button.dataset.teachers));document.querySelectorAll('[data-compare-school]').forEach(button=>button.onclick=()=>toggleCompare(button.dataset.compareSchool));}

function resetFilters(){subject='';Object.assign(filterState,{budget:'',lessons:'',curator:false,multiSubject:false});expanded=false;document.querySelectorAll('[data-subject]').forEach(button=>{const active=button.dataset.subject==='';button.classList.toggle('active',active);button.setAttribute('aria-pressed',String(active));});updateFilterUrl();renderSchools();}

if(document.body.classList.contains('school-page-body')){try{const [catalogResponse,linksResponse]=await Promise.all([fetch('/catalog.json?v=2'),fetch('/links.json')]);if(!catalogResponse.ok)throw new Error('catalog');catalog=await catalogResponse.json();await applyLiveRatings(catalog);if(linksResponse.ok)links=await linksResponse.json();document.querySelectorAll('[data-open-teacher]').forEach(button=>button.onclick=()=>teacherDetails(button.dataset.school,button.dataset.openTeacher));openDetailFromUrl(false);}catch(error){console.error(error);}}else try{const [catalogResponse,linksResponse]=await Promise.all([fetch('catalog.json?v=2'),fetch('links.json')]);if(!catalogResponse.ok)throw new Error('catalog');catalog=await catalogResponse.json();await applyLiveRatings(catalog);if(linksResponse.ok)links=await linksResponse.json();const initialParams=new URLSearchParams(location.search);subject=initialParams.get('subject')==='математика'?'математика профильная':labels[initialParams.get('subject')]?initialParams.get('subject'):'';filterState.budget=initialParams.get('budget')||'';filterState.lessons=initialParams.get('lessons')||'';filterState.curator=initialParams.get('curator')==='1';filterState.multiSubject=initialParams.get('multiSubject')==='1';$('#sort').value=initialParams.get('sort')==='name'?'name':'rating';$('#subject-list').innerHTML=[['','Все предметы'],...Object.entries(labels)].map(([value,label])=>`<button class="subject ${value===subject?'active':''}" data-subject="${value}" aria-pressed="${value===subject}">${label}</button>`).join('');document.querySelectorAll('[data-subject]').forEach(button=>button.onclick=()=>{subject=button.dataset.subject;expanded=false;document.querySelectorAll('[data-subject]').forEach(item=>{item.classList.toggle('active',item===button);item.setAttribute('aria-pressed',String(item===button));});updateFilterUrl();renderSchools();});[['#filter-budget','budget'],['#filter-lessons','lessons']].forEach(([selector,key])=>$(selector).onchange=event=>{filterState[key]=event.target.value;expanded=false;updateFilterUrl();renderSchools();});[['#filter-curator','curator'],['#filter-multisubject','multiSubject']].forEach(([selector,key])=>$(selector).onchange=event=>{filterState[key]=event.target.checked;expanded=false;updateFilterUrl();renderSchools();});$('#reset-filters').onclick=resetFilters;$('#sort').onchange=()=>{updateFilterUrl();renderSchools();};const showMore=$('#show-more');showMore.addEventListener('click',()=>{expanded=true;renderSchools();});$('#methodology').onclick=methodology;renderSchools();openDetailFromUrl(false);}catch(error){$('#school-list').innerHTML='<p>Не удалось загрузить рейтинг. Обнови страницу, чтобы попробовать ещё раз.</p>';console.error(error);}
