import { decisionFields, priceContext } from './school-content.js?v=19';
const $ = selector => document.querySelector(selector);
const escape = value => String(value).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const number = n => Number(n).toFixed(1).replace('.', ',');
const criteria = {teachers_score:'Преподаватели',practice_score:'Практика и ДЗ',feedback_score:'Проверка работ',curator_score:'Кураторы',platform_score:'Платформа',workload_score:'Нагрузка и темп',price_quality_score:'Цена / качество'};
const labels = {'русский':'Русский язык','математика':'Математика','обществознание':'Обществознание','физика':'Физика','химия':'Химия','биология':'Биология','информатика':'Информатика','английский':'Английский язык','история':'История','литература':'Литература','география':'География'};
const dialog = $('#detail-dialog');
let catalog, subject = '', expanded = false;

function showDialog(html){$('#dialog-content').innerHTML=html;dialog.showModal();document.querySelector("#dialog-content").scrollTop=0;}
$('.close').onclick=()=>dialog.close();
dialog.addEventListener('click',event=>{if(event.target===dialog){const box=dialog.getBoundingClientRect();if(event.clientX<box.left||event.clientX>box.right||event.clientY<box.top||event.clientY>box.bottom)dialog.close();}});

function methodology(){showDialog(`<div class="method-view"><h2>Как работает рейтинг</h2><p class="method-lead">Две независимые оценки складываются в один понятный результат.</p><div class="rating-formula"><div class="formula-card expert"><small>Редакция ЕГЭшки</small><strong>до 5</strong><span>по открытым данным</span></div><b class="formula-sign">+</b><div class="formula-card students"><small>Ученики</small><strong>до 5</strong><span>по одобренным отзывам</span></div><b class="formula-sign">=</b><div class="formula-card total"><small>Общий рейтинг</small><strong>до 10</strong><span>итоговая оценка</span></div></div><div class="method-note"><strong>★ Предварительная оценка</strong><span>Отзывов учеников пока недостаточно, поэтому показана только редакционная часть, пересчитанная на шкалу 0–10.</span></div><h3>Что входит в оценку ЕГЭшки</h3><div class="weight-grid"><div class="weight-item"><b>24%</b><span>Преподаватели</span></div><div class="weight-item"><b>16%</b><span>Практика</span></div><div class="weight-item"><b>14%</b><span>Проверка работ</span></div><div class="weight-item"><b>14%</b><span>Кураторы</span></div><div class="weight-item"><b>14%</b><span>Цена / качество</span></div><div class="weight-item"><b>10%</b><span>Платформа</span></div><div class="weight-item"><b>8%</b><span>Нагрузка</span></div></div><p class="trust-note"><strong>Важно:</strong> результаты учеников, которые публикуют школы, — заявления самих школ. Они не гарантируют такой же результат каждому.</p></div>`);}

function schoolDetails(name){const school=catalog.schools.find(item=>item.name===name);const top=Object.entries(school.criteria).sort((a,b)=>b[1]-a[1]).slice(0,3);showDialog(`<div class="school-detail"><div class="detail-hero"><div><h2>${escape(school.name)}</h2><p>${escape(school.description)}</p></div><div class="detail-score"><small>Оценка ЕГЭшки</small><strong>${number(school.score)}</strong><span>из 10*</span></div></div><div class="detail-subjects">${school.subjects.map(item=>`<span>${escape(labels[item]||item)}</span>`).join('')}</div><h3>Что особенно хорошо</h3><div class="detail-highlights">${top.map(([key,value])=>`<div><span>${escape(criteria[key])}</span><strong>${number(value)}</strong><i><b style="width:${value*10}%"></b></i></div>`).join('')}</div><div class="detail-grid"><article class="detail-card price"><h3>Сколько стоит</h3><p>${escape(school.price)}</p>${priceContext(school)}</article><article class="detail-card format"><h3>Формат</h3><p>${escape(school.format)}</p></article><article class="detail-card strength"><h3>Почему выбирают</h3><p>${escape(school.strengths)}</p></article><article class="detail-card attention"><h3>Что проверить</h3><p>${escape(school.weaknesses)}</p></article></div><div class="detail-footer"><p>* Предварительная редакционная оценка по открытым данным.</p><a class="button blue" href="${escape(school.url)}" target="_blank" rel="noopener">Перейти на сайт школы <span>↗</span></a></div></div>`);}

function renderSchools(){let rows=catalog.schools.filter(school=>!subject||school.subjects.includes(subject));rows.sort($('#sort').value==='name'?(a,b)=>a.name.localeCompare(b.name,'ru'):(a,b)=>b.score-a.score);$('#catalog-label').textContent=`${subject?labels[subject]:'Все предметы'} · ${rows.length} ${rows.length===1?'школа':rows.length<5?'школы':'школ'}`;$('#show-more').hidden=expanded||rows.length<=6;$('#school-list').innerHTML=rows.slice(0,expanded?rows.length:6).map((school,index)=>`<article class="school-card"><div class="school-card-top"><span class="school-mark ${index%2?'pink-mark':'blue-mark'}">${school.name.startsWith('100')?'100':escape(school.name.slice(0,1))}</span><span class="rank">${$('#sort').value==='rating'?`${index+1} место`:'Онлайн-школа'}</span></div><h3>${escape(school.name)}</h3>${decisionFields(school)}<div class="card-score"><span>Оценка ЕГЭшки</span><strong>${number(school.score)}<small>/10*</small></strong></div><button class="card-open" data-school="${escape(school.name)}">Подробнее о школе <span>↗</span></button></article>`).join('');document.querySelectorAll('[data-school]').forEach(button=>button.onclick=()=>schoolDetails(button.dataset.school));}

try{const response=await fetch('catalog.json');if(!response.ok)throw new Error('catalog');catalog=await response.json();$('#subject-list').innerHTML=[['','Все предметы'],...Object.entries(labels)].map(([value,label])=>`<button class="subject ${value===''?'active':''}" data-subject="${value}" aria-pressed="${value===''}">${label}</button>`).join('');document.querySelectorAll('[data-subject]').forEach(button=>button.onclick=()=>{subject=button.dataset.subject;expanded=false;document.querySelectorAll('[data-subject]').forEach(item=>{item.classList.toggle('active',item===button);item.setAttribute('aria-pressed',String(item===button));});renderSchools();});$('#sort').onchange=renderSchools;$('#show-more').onclick=()=>{expanded=true;renderSchools();};$('#methodology').onclick=methodology;renderSchools();}catch(error){$('#school-list').innerHTML='<p>Не удалось загрузить рейтинг. Обнови страницу, чтобы попробовать ещё раз.</p>';console.error(error);}
