// Generated by export_catalog.py; subject order preserves bot deep links.
export const labels = {"русский": "Русский язык", "математика профильная": "Математика профильная", "обществознание": "Обществознание", "физика": "Физика", "химия": "Химия", "биология": "Биология", "информатика": "Информатика", "английский": "Английский язык", "история": "История", "литература": "Литература", "география": "География", "математика базовая": "Математика базовая"};
export const quizSubjectKeys = Object.keys(labels);
export const teacherSubjects = teacher => teacher.subjects || [teacher.subject];
